sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"
  - "16"

git:
  autocrlf: input

os:
  - linux
  - windows
  - osx
  - freebsd

before_install:
  - npm cache clean
  - travis_retry npm install

script:
  - npm test
